version: '3'
services:
  laravel:
    build: 
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: lucabelezal/laravel:prod
    container_name: laravel
    networks:
      - laranet
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: lucabelezal/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"
networks:
  laranet:
    driver: bridge
